/* tslint:disable */
/* eslint-disable */
/**
 * Product catalog API
 * This is a simple \'Product catalog\' service for e-shops
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A product information for the store
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Uniq id
     * @type {string}
     * @memberof Product
     */
    'id': string;
    /**
     * Title of the product
     * @type {string}
     * @memberof Product
     */
    'title': string;
    /**
     * Description of the product
     * @type {string}
     * @memberof Product
     */
    'description': string;
    /**
     * Price of the product
     * @type {number}
     * @memberof Product
     */
    'price': number;
    /**
     * Amount of the product in store
     * @type {number}
     * @memberof Product
     */
    'count': number;
}

