/* tslint:disable */
/* eslint-disable */
/**
 * Product catalog API
 * This is a simple \'Product catalog\' service for e-shops
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
export * from "./product/model";
